spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 12345678
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
mybatis:
  type-aliases-package: com.ordosbank
  mapper-locations: classpath*:/mybatis-mappers/*
files:
  path: ${file-path:/Users/haoshuai/GlobalUpload/doc}
logging:
  config: classpath:logback-spring.xml
log:
  level:
    root: info
    my: debug
  file: log/wo/wo.log
  maxsize: 30MB
token:
  expire:
    seconds: 86400
server:
  port: 8088
  servlet:
    context-path: /wo
upload:
  serverUrl: http://localhost:8088/
